server:
  port: 8091  #端口号
spring:
  application:
    name: usian-item-web  #向注册中心注册的名称
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/  #注册中心的地址

fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.159.132:22122