server:
  port: 8090 #端口号
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册中心地址
spring:
  application:
    name: usain-item-service  #向注册中心注册的名称
    #连接数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usian?characterEncoding=UTF-8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.159.133:7001
        - 192.168.159.133:7002
        - 192.168.159.133:7003
        - 192.168.159.133:7004
        - 192.168.159.133:7005
        - 192.168.159.133:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接

#配置缓存首页商品分类的 key
PROTAL_CATRESULT_KEY: PROTAL_CATRESULT_KEY