spring:
  application:
    name: usian-search-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    elasticsearch:   #es索引链接
      cluster-nodes: 192.168.159.134:9200,192.168.159.135:9200
  rabbitmq:
    host: 192.168.159.136
    port: 5672
    username: admin
    password: 1111
    virtual-host: /
server:
  port: 8095
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#索引名称
ES_INDEX_NAME: usian
#类型名称
ES_TYPE_NAME: item